name: Build and Deploy

on:
  push:
    branches:
      - main # You can specify other branches if needed.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x" # Ensure this matches your Node version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }} # This will be set to 82.112.239.91
          USERNAME: ${{ secrets.USERNAME }} # This will be set to u472469429
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -P 65002 -r build/* $USERNAME@$HOST:/home/u472469429/domains/leso.online/public_html
          rm private_key.pem
